server {
    listen 80;

    server_name _;

    # Maximum upload size
    client_max_body_size 20M;

    # Laravel public directory
    root /var/www/html/public;

    index index.php index.html;


    # =========================================================
    # Laravel Routes
    # =========================================================
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    # =========================================================
    # PHP-FPM
    # =========================================================
    location ~ \.php$ {

        # Prevent direct access to non-existing PHP files
        try_files $uri =404;

        # PHP-FPM container
        fastcgi_pass ehkam-app:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        # Laravel front controller
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;

        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }


    # =========================================================
    # Security
    # =========================================================

    # Do not allow access to hidden files
    location ~ /\. {
        deny all;
    }
}